# Generated by Django 4.2.7 on 2023-12-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event_app", "0003_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="club",
            new_name="club_1",
        ),
    ]
