# Generated by Django 4.2.7 on 2024-01-27 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("event_app", "0007_feedback_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Join_request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "club_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event_app.club"
                    ),
                ),
            ],
        ),
    ]
