# Generated by Django 4.2.7 on 2024-02-08 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event_app", "0009_join"),
    ]

    operations = [
        migrations.RenameField(
            model_name="join",
            old_name="user_2",
            new_name="user",
        ),
    ]
